### ISSUE TITLE
Project is not working properly

### ISSUE THREAD

**Issue by aaryanXcode** [yuki00yossi/smart_alert#10]
I visited demo web page via this link "https://yuki00yossi.github.io/smart_alert/"  and checked multiple times on my browser and incognito both, it has error of file,css and js files are not properly linked

**Comment by aaryanXcode** [comment]
I can fix this issue,Please let me know!

**Comment by yuki00yossi** [comment]
Thanks for reporting the bug and fixing it!
I appreciate your contribution!

**Comment by yuki00yossi** [comment]
Closed due to completed
