### ISSUE TITLE
improve the design of alerts.

### ISSUE THREAD

**Issue by yuki00yossi** [yuki00yossi/smart_alert#2]
The current problem is that if you push a second alert before you delete one alert, it will overlap.
I would like to change this so they don't overlap.

**Comment by NinfarZ** [comment]
Is help still needed here? If so, what kind of design improvements are we looking for?

**Comment by yuki00yossi** [comment]
@NinfarZ 
Thanks for the comment!
Sorry for the abstract issue.
The current problem is that if you push a second alert before you delete one alert, it will overlap.
I would like to change this so they don't overlap.

**Comment by yuki00yossi** [comment]
I have edited my comment on this issue.

**Comment by NinfarZ** [comment]
I see! Would you want the alerts to replace the previous one? Or to stack vertically?
I would like to work on this issue.

**Comment by yuki00yossi** [comment]
Thank you for saying that, it's nice to hear!
I think it's better to arrange the alerts vertically if there are multiple alerts, because if you use a specification that erases the previous alert, what you want to tell the user will be lost.

I have made a video of my image, please watch it.
However, this is just my opinion, so if you have a better opinion, please let me know.

Best regards,

https://user-images.githubusercontent.com/44756367/225356827-39fad1cf-aaf7-48d9-87aa-75fdb6de2cd3.mp4

**Comment by NinfarZ** [comment]
Yes, I think that's a good idea. Also for the alerts that appear at the bottom. Maybe they could stack upwards instead?

**Comment by yuki00yossi** [comment]
That's a great idea! Let's go with that.

**Comment by yuki00yossi** [comment]
Thanx to @NinfarZ , the problem raised in this isssue has been resolved, so I am closing it.
Thank you!
